[Uncaught HttpErrorResponse] Parse text response as json
The code breaks with the error below. Parsing the response as JSON makes the error go away in Angular 8.

```
Uncaught HttpErrorResponse
...
error: SyntaxError: Unexpected token o in JSON at position 0 at JSON.parse (<anonymous>) at XMLHttpRequest.onLoad 
...
message: "Unexpected token o in JSON at position 0"
...
text: "ok"
```